name: Build and deploy Docker app  DOCKER HUB

on:
  push:
    branches: [main, staging]
    paths:
      - src/**
      - 'package.json'
      - .github/**
      - './*'

env:
  ORACLE_VM_PRIVATE_KEY: ${{secrets.ORACLE_PRIVATE_KEY}}
  ORACLE_VM_URL: ${{secrets.ORACLE_VM_URL}}
  ORACLE_USERNAME: ${{secrets.ORACLE_USERNAME}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set permissions for private key
        run: |
          echo "${{ secrets.ORACLE_VM_PRIVATE_KEY }}" > nothandoracle.key
          chmod 600 nothandoracle.key
      - name: SSH into EC2 instance and navigate to repo and reset branch to main
        run: |
          ssh -o StrictHostKeyChecking=no -i nothandoracle.key $ORACLE_USERNAME@$ORACLE_VM_URL <<EOF
          cd repos/whatsapp-webjs &&
          rm -rf node_modules &&
          git fetch --all &&
          git reset --hard origin/main &&
          sudo npm install
          EOF

      - name: Restart app using pm2
        run: |
          ssh -o StrictHostKeyChecking=no -i  nothandoracle.key $ORACLE_USERNAME@$ORACLE_VM_URL 'pm2 restart soccer'
